version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  Build-and-Test:
    docker:
      - image: cimg/python:3.11.2
    steps:
      - checkout
      - run:
          name: Build
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Test
          command: |
            . venv/bin/activate
            python3 manage.py test

workflows:
  Django-Test-workflow:
    jobs:
      - Build-and-Test
      - docker/publish:
          image: circleci-django